language: csharp
mono:
  - latest
env: WALLEE_SDK_VERSION=1.0.0
solution: Customweb.Wallee.sln
script:
  - /bin/sh ./build.sh
  - /bin/sh ./test.sh
deploy:
  skip_cleanup: true
  provider: script
  script:
    - /bin/sh ./deploy.sh
  on:
    tags: true
