language: csharp
mono:
  - latest
env: WALLEE_SDK_VERSION=1.0.1
solution: Customweb.Wallee.sln
script:
  - /bin/sh ./build.sh
  - /bin/sh ./test.sh
deploy:
  provider: script
  script:
    - /bin/sh ./deploy.sh
  on:
    tags: true
